### ISSUE TITLE
sorry needs developing

### ISSUE THREAD

**Issue by satbopper** [magtimmermans/com.cyclone-software.buienalarm#1]
It rains cats and dogs here,app installed flow made and nothing not even a single message
i presume the location is automatic

**Comment by canedje** [comment]
Same over here no warning or trigger.
The logfile shows mm rain every 5 minutes, But no trigger in a flow

**Comment by magtimmermans** [comment]
Please tell which version you use and what kind of trigger.

**Comment by satbopper** [comment]
i use version 1.1.0 
a lot of rain in the log
als  ---- het gaar regenen over 5 min
dan stuur een push message

**Comment by magtimmermans** [comment]
is fixed in next version (I hope)
