### ISSUE TITLE
Rain but no alarm

### ISSUE THREAD

**Issue by henkbart** [magtimmermans/com.cyclone-software.buienalarm#10]
Hello,

i am using version 1.15 of your app,
Today i noticed that it was raining but no alarms coming from your app, When viewing the next 2 hours shows 0 mm.
Dark Weather app shows 0,29mm of rain....
Is there a problem with your app??

Henk

**Comment by magtimmermans** [comment]
I am not sure. Please check the buienalarm app as well to make sure that they display the same. Sometimes the internet connection is bad and then it shows all 0.

**Comment by magtimmermans** [comment]
New version
