### ISSUE TITLE
temperature

### ISSUE THREAD

**Issue by groetsels** [magtimmermans/com.cyclone-software.buienalarm#11]
Is it possible for you to add the temperature as an event.
Then I can UseNext it to check ik the app is stil runnen when it changes.
I have had several times that the app had the old values of Horus ago.

**Comment by magtimmermans** [comment]
Even in het Nederlands :) Ik snap niet helemaal wat je bedoelt. Want de temp kan bijvoorbeeld een paar uur gelijk blijven en helpt dan niet.

**Comment by groetsels** [comment]
Hoi Marcel,

Fijn dat ik het je even in het Nederlands mag uitleggen.

In Homey kan ik nu nergens zien of testen of de koppeling met BuienAlarm
het nog doet.
Ik heb nu reeds meerdere keren gehad dat er geen nieuwe data werd opgehaald.
Door te testen of de temperatuur veranderd weet ik in ieder geval een
aantal keer per dag dat de koppeling nog werkt.
Dat de temperatuur een paar uur achter elkaar gelijk zou kunnen blijven
klopt.
Vorige week heb ik ergens gezien dat BuienAlarm was blijven steken, na een
herstart werkt het weer.

Verder wil ik toch wel even zeggen dat je mooie apps maakt.
Ik gebruik er toch wel een stuk of 3. (buien-alarm, life-360, zonnestanden)

N.B. het verschil met BuienRadar best groot.

[image: image.png]




Op ma 11 okt. 2021 om 12:54 schreef magtimmermans ***@***.***

**Comment by magtimmermans** [comment]
Allereerst dankjewel. Stel de temperatuur verandert niet. Dan weet je nog steeds niet of de App hangt of niet. De buienradar app haalt elke 5 minuten nieuwe data op.  Wellicht dat ik hier een trigger op kan zetten. Ik heb gisteren een nieuwe versie vrij gegeven met verbeterde functies om data op te halen. Ik heb wel een paar keer gezien dat de api die ik gebruik soms wel een dag niet werkt. Wellicht kan ik rond om dit wat meer checks doen en waarschuwingen geven.

**Comment by groetsels** [comment]
Hoi Marcel,
Dat BuienAlarm soms niet werkt had ik ook al gemerkt aan de website. Deze
geeft ook vaak geen reactie, terwijl de app dan wel data ophaalt.
In mij Homey heb ik meerdere controle routines zitten of app's nog werken
en of sensors nog rapporteren.
's Nachts worden evt. app's herstart. als er geen reactie geweest is.
Of BuienAlarm daar ook tussen moet komen te staan, is en mogelijkheid. Als
overdag de temperatuur slechts 1 keer verandert, hoef je niet te herstarten.
Maar kies zelf maar even welk mechanisme je toepast.
Ik heb de update voorbij zien komen wellicht helpt dat al. :-)
Ik blijf even de verschillen tussen BuienAlarm en BuienRadar bekijken. Veel
komt overeen.
Ik gebruik het alleen om het zonnescherm in de doen als het gaat regenen.
(en dat kan voorlopig op beide "het gaat regenen" events.)

Carel

[image: image.png]

Op di 12 okt. 2021 om 12:33 schreef magtimmermans ***@***.***

**Comment by magtimmermans** [comment]
https://homey.app/a/com.cyclone-software.buienalarm/test/
