### ISSUE TITLE
Current version stopt working

### ISSUE THREAD

**Issue by magtimmermans** [magtimmermans/com.cyclone-software.buienalarm#12]
The current API of buienrader stopt working and therefor also the app. There is here a link to the new test version:

https://homey.app/a/com.cyclone-software.buienalarm/test/

**Comment by corvdniet** [comment]
I had the impression that the old version worked again. I checked the new test version, but is seems that the rain data is always 0
EDIT: The line above is about the config screen. The rest works like a charm

**Comment by magtimmermans** [comment]
Okay, i see it. I will update this.

**Comment by magtimmermans** [comment]
Hi, I have updated a next version that have a fixed config screen.

**Comment by corvdniet** [comment]
Looking good. Thanks a lot

**Comment by corvdniet** [comment]
Unfortunately, the data in the config screen and the data on the website buienalarm.nl do not match for my location.

**Comment by magtimmermans** [comment]
That's weird as i retrieve the data from the website. Could you make pictures from both of them. I know that tge website dies not display data within a small threshold <0.05 or so.

**Comment by corvdniet** [comment]
I made screenprints of the android app and of the config screen. The amount
of rain on the config screen does not match with the zero rain forcast in
the app

Op wo 6 okt. 2021 21:50 schreef magtimmermans ***@***.***>:

**Comment by magtimmermans** [comment]
Could you share those to see what the difference is?

**Comment by corvdniet** [comment]
Sorry for that. Here they are:
![Screenshot_20211006-215840_Homey](https://user-images.githubusercontent.com/22527207/136434682-0d4194ec-9745-4a21-a65e-8e7b45c6c8e7.jpg)
![Screenshot_20211006-215933_Buienalarm](https://user-images.githubusercontent.com/22527207/136434715-e0696094-5db6-4ab2-b592-06c87c2d0231.jpg)

**Comment by magtimmermans** [comment]
Very strange. I will investigate this in the weekend.

**Comment by magtimmermans** [comment]
I have made an update. The loop to display the numbers went crazy.

**Comment by corvdniet** [comment]
Thanks. All we need now is a little bit of rain to check the new version ;-)

**Comment by corvdniet** [comment]
Works as expected. Thanks a lot. Gave you some beer-money (PayPal) 👍

**Comment by magtimmermans** [comment]
Thank you very much!!

**Comment by DeWoltie** [comment]
Hi mine is stopped working as in the time stamp and values in de app, see below screenshot. What should I do to fix this? 
![DD9632D7-057E-4F5B-93D4-A885611CF5A8](https://user-images.githubusercontent.com/73881169/148034180-b8b49794-0488-40dd-a062-5203face63cd.png)
