### ISSUE TITLE
Request: Add max temp as tag?

### ISSUE THREAD

**Issue by iisworks** [magtimmermans/com.cyclone-software.buienalarm#14]
Thanks for the app, I use it to close the sun screen when rain is expected. I also only extend the screen when T >20C today (currenly with the Knmi app).

1) I don't know if the buienalarm api even provides it, but would it be possible to expose the "Expected Max Temperature Today" as a tag? And maybe having the min and current temp would be a nice addition too.

![image](https://user-images.githubusercontent.com/33196233/180647232-4eb76d01-eadd-4ffa-84c2-997b2bc445e7.png)

2) Some typos:

Cards:
- Comming -> Coming
- more then -> more than
Suggestion:
"It is going to <xxx> rain in ..." -> "XXX rain expected in ..." (e.g. "Light rain expected in ...")

App config: 
- Tempature -> Temperature
- Moderated Rain -> Moderate Rain 
- Light regen -> Light Rain

**Comment by magtimmermans** [comment]
https://homey.app/a/com.cyclone-software.buienalarm/test/
