### ISSUE TITLE
Compatible with homey pro 2023

### ISSUE THREAD

**Issue by pjmpessers** [magtimmermans/com.cyclone-software.buienalarm#15]
Hello

I like this app. Is it possible to make it compatible with homey pro 2023 by writing it in sdkv3.

Thanks a lot.

**Comment by magtimmermans** [comment]
Could you please test the app and let me know if there is an error?
SDK 3 version: https://homey.app/a/com.cyclone-software.buienalarm/test/

**Comment by pjmpessers** [comment]
Wow. That was quick. I installed it, and it looks it's working great. It immediately shows how much rain can fall every 5 minutes. On this moment i have know flows. Untill i have a automated sunscreen.

**Comment by pjmpessers** [comment]
Thanks for the update. Paid a small fee.



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: magtimmermans ***@***.***>
Datum: 15-10-2022 13:16 (GMT+01:00)
Aan: "magtimmermans/com.cyclone-software.buienalarm" ***@***.***>
Cc: Pieter ***@***.***>, Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.buienalarm] Compatible with homey pro 2023 (Issue #15)


Could you please test the app and let me know if there is an error?
SDK 3 version: https://homey.app/a/com.cyclone-software.buienalarm/test/

**Comment by magtimmermans** [comment]
Thanks!!

**Comment by Christianmous** [comment]
I've just installed the app. To test it i let the app send a push message when it starts raining. After this i will hook up my sunscreen etcetera but now for testing just a push message. I don't get any message of the homey pro. Yesterday it was a perfect day to test it with lot's of dry periods (half an hour or so) and also a lot of rainy moments. In no situation i get a message. Am i missing something? I'm using Homey Pro version 10.1.0. The version of the app is 4.0.0. Hope you can enlighten me.

**Comment by Christianmous** [comment]
Number i got after reporting / diagnose is: 620435a6-b4b9-4634-82dd-d30d7e6d76a8
