### ISSUE TITLE
Compatible with Homey Bridge

### ISSUE THREAD

**Issue by keitje** [magtimmermans/com.cyclone-software.buienalarm#16]
Hello, I am a Homey Bridge user and I want to use your weather information. Is there a possibility for compatibility with the Homey Bridge version (in the future)?

**Comment by magtimmermans** [comment]
Hi, no. This requires me a payed developer account from homey. Currently I only use my home to support the current apps. In my home automation I am switched to Home Assistant

**Comment by keitje** [comment]
Understandable! Thank you for your quick response.
