### ISSUE TITLE
RainLevel 0mm bij 0.xmm

### ISSUE THREAD

**Issue by michaelw85** [magtimmermans/com.cyclone-software.buienalarm#19]
**Probleem**
Ik heb een flow waarin ik aangeeft dat er over een uur Xmm regen wordt verwacht.
Afgelopen dagen is er veel mot regen en dan hebben we het over b.v. 0.2mm regen. 
In mijn melding wordt dit 0mm bij gebruik van de `RainLevel` tag en ik dacht initieel dat de tag niet goed werkte tot ik in de config de lage waardes zag staan.

**Voorstel**
Ik zou de afronding er denk ik uithalen of alleen toepassen bij meer dan 1mm regen.
Als ik de code bekijk zit het denk ik hier: https://github.com/magtimmermans/com.cyclone-software.buienalarm/blob/master/app.js#L113

**Flow**
_Als_
- Het gaat regenen over 1h

_En_ (niet relevant denk ik)
- Het niet regent
- Var "rain_notification_sent" gelijk is aan nee

_All_  

_Dan_
- Stuur "🌧️  #RainLevel mm regenen verwacht over een uur." naar iedereen
- Maak notificatie (zelfde melding)
- Zet var "rain_notification_sent" naar ja

Ik heb zelf nog geen actieve homey app dev gedaan maar zou dit misschien wel als een eerst dingetje kunnen oppakken als je het ermee eens bent.

**Comment by magtimmermans** [comment]
Hoi Michael,

De code daar is oud en niet meer compleet actueel. Ik gebruik nu een locale github dat werkt voor mij handiger en heeft meer functionaliteit (AI oa).

Daarnaast is de method die je beschrijft voor de berekening hoeveel regen er valt (procentueel) in 2 uur tijd.

Wat wil je precies? Dat je een melding krijgt van regen onder de 0.2 mm?

Groetjes,

Marcel


From: Michael Withagen ***@***.***>
Sent: Saturday, 21 December 2024 10:43
To: magtimmermans/com.cyclone-software.buienalarm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [magtimmermans/com.cyclone-software.buienalarm] RainLevel 0mm bij 0.xmm (Issue #19)


Probleem
Ik heb een flow waarin ik aangeeft dat er over een uur Xmm regen wordt verwacht.
Afgelopen dagen is er veel mot regen en dan hebben we het over b.v. 0.2mm regen.
In mijn melding wordt dit 0mm bij gebruik van de RainLevel tag en ik dacht initieel dat de tag niet goed werkte tot ik in de config de lage waardes zag staan.

Voorstel
Ik zou de afronding er denk ik uithalen of alleen toepassen bij meer dan 1mm regen.
Als ik de code bekijk zit het denk ik hier: https://github.com/magtimmermans/com.cyclone-software.buienalarm/blob/master/app.js#L113

Flow
Als

  *   Het gaat regenen over 1h

En (niet relevant denk ik)

  *   Het niet regent
  *   Var "rain_notification_sent" gelijk is aan nee

All

Dan

  *   Stuur "🌧️ #RainLevel mm regenen verwacht over een uur." naar iedereen
  *   Maak notificatie (zelfde melding)
  *   Zet var "rain_notification_sent" naar ja

Ik heb zelf nog geen actieve homey app dev gedaan maar zou dit misschien wel als een eerst dingetje kunnen oppakken als je het ermee eens bent.

**Comment by michaelw85** [comment]
> Wat wil je precies? Dat je een melding krijgt van regen onder de 0.2 mm?

Mijn verwachting zou zijn dat RainLevel niet een afgerond getal is maar met 1 decimaal. Met name in de situatie dat het onder de 1mm is. De melding "over een uur valt er 0mm regen" is natuurlijk wat vreemd in mijn situatie.

**Comment by magtimmermans** [comment]
Ok. We hebben 2 dingen. Een RainLevel token (die rond ik niet af) en is de regen level binnen 5 minuten die er valt:
`await this.RainLevelToken.setValue(parseFloat(result.rainData[0])).catch(err => this.error(err));
`
Of een trigger met regen, dat is een berekening van all regen totaal van 1 uur. Rond ik af op 2 decimalen.

**Comment by michaelw85** [comment]
Ik maak dan gebruik van de trigger over 1h gaat het regenen, de token krijgt in die situatie als waarde 0 bij mij.

![Screenshot_20241222-135034~2](https://github.com/user-attachments/assets/7258788e-288b-40bb-ba91-096f8596503b)

Er is een klein beetje regen gevallen rond deze tijden.
Dit is de data van mijn regen meter:
![Screenshot_20241222-135401](https://github.com/user-attachments/assets/94fca992-638f-4027-9c0d-989f6e270e70)

Gaat er dan misschien iets mis bij het optellen want de trigger is wel terecht afgevuurd.

**Comment by magtimmermans** [comment]
Als de trigger afgaat en je lees de RainLevel token uit, die kan dan best 0 zijn omdat hij het eerste data punt pakt van de array van 24. De trigger pakt de som van de eerste 12. 
bijvoorbeeld: [0,0,0.1,0.4,0.3,0,0,0,0,0,0,12]
hier mee gaat de trigger af maar RainLevel token is 0.

**Comment by michaelw85** [comment]
Aah dat verklaart de 0mm. Is er al een manier om aan de som voor het aankomend uur te komen?

**Comment by magtimmermans** [comment]
Ik zal een nieuw token toevoegen met de uurwaarde.

**Comment by michaelw85** [comment]
Dankjewel dat je deze uitbreiding wilt doen!

**Comment by magtimmermans** [comment]
Geen probleem: https://homey.app/a/com.cyclone-software.buienalarm/test/

**Comment by michaelw85** [comment]
Ik heb de test versie geinstalleerd en tag in mijn flow aangepast! Nu even wachten tot het gaat regenen 😂

**Comment by michaelw85** [comment]
De eerste waardes zijn al binnen van 0,2mm, zag nog wel een 0 voorbij komen die ik nog niet kan plaatsen.
