### ISSUE TITLE
version 1.1.2

### ISSUE THREAD

**Issue by satbopper** [magtimmermans/com.cyclone-software.buienalarm#3]
For the first time i got a notification that in the amount of time it will start to rain,so that is ok
more checkups when rain starts would be nice because correct me if i am wrong,if it starts to rain at 07.00 until 10.00 then you only get a message at somewhere 07.00 ??

today is the day for checking and for me the ammount of given messages is sufficient so well done

**Comment by canedje** [comment]
When will this version available at betha?
Because at this moment the app is of no use

**Comment by magtimmermans** [comment]
It is already available as beta.
