### ISSUE TITLE
Trigger it's going to rain in... not working

### ISSUE THREAD

**Issue by larsnet** [magtimmermans/com.cyclone-software.buienalarm#5]
I have a test trigger to send me a message 15mins before it's rains And also set a variable to true. It was a rainy day today but the trigger didn't run.

When I use the trigger total rain in a hour more then for example 0.1 works.

**Comment by larsnet** [comment]
Nevermind the trigger runs this morning.

**Comment by jorritv8hoven** [comment]
After the last update there is no trigger for the flow. IT worked before update. Die tey ptp, but didnot work
