### ISSUE TITLE
Minuten setting werkt niet. 

### ISSUE THREAD

**Issue by TinoS1964** [magtimmermans/com.cyclone-software.buienalarm#9]
Ik gebruik de bèta versie, de weergave in de buienalarm instellingen werkt goed tov de stable.

Als ik deze app als trigger gebruik gaat er wat mis. 
Ik gebruik de trigger "het gaat regenen over x minuten" 
Het maakt niet uit welke minuten setting ik kies. 
De flow wordt pas actief als het gaat regenen en niet eerder.

**Comment by magtimmermans** [comment]
Okay, ga ik naar kijken

**Comment by TinoS1964** [comment]
Al wat gevonden?
